services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
