version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"


  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "3307:3306"  # שנה את הפורט החיצוני ל-3307

  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_USER=flask_user
      - MARIADB_PASSWORD=flask_password
      - MARIADB_DB=flask_db
    depends_on:
      - redis
      - mariadb
